/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import gestores.GestorAsignarEvaluadores;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author gimena
 */
public class PantallaAsignarEvaluadoresTI extends javax.swing.JFrame {

    /**
     * Creates new form PantallaAsignarEvaluadoresTI
     */
    public PantallaAsignarEvaluadoresTI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_Chair = new javax.swing.JLabel();
        lbl_simposio = new javax.swing.JLabel();
        btn_siguiente = new javax.swing.JButton();
        btn_Atras = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        TabbedPanePasos = new javax.swing.JTabbedPane();
        pnl_paso1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_AutoresPorTI = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btn_Ascendente = new javax.swing.JButton();
        btn_Descendente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Evaluadores = new javax.swing.JTable();
        pnl_paso2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_TI = new javax.swing.JTable();
        btn_aceptarTISeleccionedos = new javax.swing.JButton();
        pnl_paso3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbl_EvaluadoresDisponibles = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lista_CantTIPorEvaluador = new javax.swing.JList<>();
        pnl_paso4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lista_TIyEvaluadores = new javax.swing.JList<>();
        btn_Confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Asignar Evaluadores a Trabajos de Investigación ");

        lbl_Chair.setText("Chair: ");

        lbl_simposio.setText("Edición de SImposio: ");

        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        btn_Atras.setText("Atras");
        btn_Atras.setEnabled(false);
        btn_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtrasActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        TabbedPanePasos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPanePasosStateChanged(evt);
            }
        });
        TabbedPanePasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabbedPanePasosMouseClicked(evt);
            }
        });

        jLabel4.setText("Trabajos de Investigación: ");

        tbl_AutoresPorTI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Nº de Orden", "Autores"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_AutoresPorTI);
        if (tbl_AutoresPorTI.getColumnModel().getColumnCount() > 0) {
            tbl_AutoresPorTI.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel5.setText("Ordenar Evaluadores: ");

        btn_Ascendente.setText("Ascendente");
        btn_Ascendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AscendenteActionPerformed(evt);
            }
        });

        btn_Descendente.setText("Descendente");

        tbl_Evaluadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Apellido", "Nombre", "Categoría", "Tipo de Títulos", "Grupo de Investigación", "Centro de Investigación", "Facultad", "Universidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_Evaluadores);

        javax.swing.GroupLayout pnl_paso1Layout = new javax.swing.GroupLayout(pnl_paso1);
        pnl_paso1.setLayout(pnl_paso1Layout);
        pnl_paso1Layout.setHorizontalGroup(
            pnl_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_paso1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_paso1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Ascendente)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Descendente))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_paso1Layout.setVerticalGroup(
            pnl_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_paso1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btn_Ascendente)
                    .addComponent(btn_Descendente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        TabbedPanePasos.addTab("Inicio", pnl_paso1);

        jLabel6.setText("Seleccione Trabajos de Investigación");

        tbl_TI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número de Orden", "Nombre"
            }
        ));
        jScrollPane3.setViewportView(tbl_TI);

        btn_aceptarTISeleccionedos.setText("Aceptar");
        btn_aceptarTISeleccionedos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarTISeleccionedosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_paso2Layout = new javax.swing.GroupLayout(pnl_paso2);
        pnl_paso2.setLayout(pnl_paso2Layout);
        pnl_paso2Layout.setHorizontalGroup(
            pnl_paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_paso2Layout.createSequentialGroup()
                .addGroup(pnl_paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_paso2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(pnl_paso2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_aceptarTISeleccionedos)))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        pnl_paso2Layout.setVerticalGroup(
            pnl_paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_paso2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_aceptarTISeleccionedos)
                    .addGroup(pnl_paso2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        TabbedPanePasos.addTab("Selección Trabajos", pnl_paso2);

        jLabel7.setText("Selecciones para cada Trabajo de Investigación 3 (tres) Evaluadores");

        jLabel8.setText("Se deberia panel para cada TI. O buscar otra forma.");

        jLabel10.setText("//Trabajo de Investigación");

        tbl_EvaluadoresDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Evaluadores Disponibles"
            }
        ));
        jScrollPane7.setViewportView(tbl_EvaluadoresDisponibles);

        jLabel9.setText("Cantidad de Trabajos de Investigacion por Evaluador");

        lista_CantTIPorEvaluador.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Evaluador1:  12", "Evaluador2:    5", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(lista_CantTIPorEvaluador);

        javax.swing.GroupLayout pnl_paso3Layout = new javax.swing.GroupLayout(pnl_paso3);
        pnl_paso3.setLayout(pnl_paso3Layout);
        pnl_paso3Layout.setHorizontalGroup(
            pnl_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_paso3Layout.createSequentialGroup()
                .addGroup(pnl_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_paso3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(pnl_paso3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnl_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_paso3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(pnl_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(pnl_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_paso3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addContainerGap())
        );
        pnl_paso3Layout.setVerticalGroup(
            pnl_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_paso3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(5, 5, 5)
                .addGroup(pnl_paso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_paso3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        TabbedPanePasos.addTab("Selección Evaluadores", pnl_paso3);

        jLabel11.setText("Evaluadores Seleccionados para cada Trabajo de Investigación");

        lista_TIyEvaluadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "//nombreTI1: nomYApeEva1,  nomYApeEva2, nomYApeEva3.", "//nombreTI2: nomYApeEva1,  nomYApeEva2, nomYApeEva3.", "//nombreTI3: nomYApeEva1,  nomYApeEva2, nomYApeEva3.", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(lista_TIyEvaluadores);

        btn_Confirmar.setText("Confirmar");
        btn_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_paso4Layout = new javax.swing.GroupLayout(pnl_paso4);
        pnl_paso4.setLayout(pnl_paso4Layout);
        pnl_paso4Layout.setHorizontalGroup(
            pnl_paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_paso4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_paso4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btn_Confirmar)
                .addGap(49, 49, 49))
        );
        pnl_paso4Layout.setVerticalGroup(
            pnl_paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_paso4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnl_paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Confirmar)
                    .addGroup(pnl_paso4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        TabbedPanePasos.addTab("Finalización", pnl_paso4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lbl_simposio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabbedPanePasos)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_Chair)
                                .addGap(178, 178, 178))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_siguiente)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Cancelar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(lbl_Chair)
                .addGap(24, 24, 24)
                .addComponent(lbl_simposio)
                .addGap(18, 18, 18)
                .addComponent(TabbedPanePasos, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_siguiente)
                    .addComponent(btn_Atras)
                    .addComponent(btn_Cancelar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AscendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AscendenteActionPerformed
        // TODO add your handling code here:
        //Metodo que ordena a los Evaladores en orden ascendente segun su categoria.
        btn_Descendente.setEnabled(false);
        // Desabilita boton descentende porque no esta programado.
    }//GEN-LAST:event_btn_AscendenteActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null,"Se perderán datos. ¿Esta seguro que desea salir?");
        {
            hide();
            dispose();
        }
        //Cierra ventana y vuelve a la ventana anterior
    }//GEN-LAST:event_btn_CancelarActionPerformed
    private void btn_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtrasActionPerformed
        if(pnl_paso2.isShowing())
        {
            pnl_paso1.show(true);
            btn_Atras.setEnabled(false);
            btn_siguiente.setEnabled(true);
        }
        if(pnl_paso3.isShowing())
        {
            pnl_paso2.show(true);
            btn_siguiente.setEnabled(true);
            btn_Atras.setEnabled(true);
        }
        if(pnl_paso4.isShowing())
        {
            pnl_paso3.show(true);
             btn_siguiente.setEnabled(true);
            btn_Atras.setEnabled(true);
        }
        
    }//GEN-LAST:event_btn_AtrasActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
       if(pnl_paso1.isShowing())
        {
            pnl_paso2.show(true);
            btn_Atras.setEnabled(true);
            btn_siguiente.setEnabled(true);
        }
        if(pnl_paso2.isShowing())
        {
            pnl_paso3.show(true);
            btn_siguiente.setEnabled(true);
            btn_Atras.setEnabled(true);
        }
        if(pnl_paso3.isShowing())
        {
            pnl_paso4.show(true);
             btn_siguiente.setEnabled(false);
            btn_Atras.setEnabled(true);
        }
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void TabbedPanePasosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPanePasosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TabbedPanePasosStateChanged

    private void TabbedPanePasosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabbedPanePasosMouseClicked
        // TODO add your handling code here:
        if(pnl_paso1.isShowing())
        {
            btn_Atras.setEnabled(false);
            btn_siguiente.setEnabled(true);
        }
        if(pnl_paso2.isShowing() || pnl_paso3.isShowing())
        {
            btn_siguiente.setEnabled(true);
            btn_Atras.setEnabled(true);
        }
       
        if(pnl_paso4.isShowing())
        {
             btn_siguiente.setEnabled(false);
            btn_Atras.setEnabled(true);
        }
    }//GEN-LAST:event_TabbedPanePasosMouseClicked

    private void btn_aceptarTISeleccionedosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarTISeleccionedosActionPerformed
        // TODO add your handling code here:
        //acepta TI seleccionados y muestra cantidad de ti por evaluador
    }//GEN-LAST:event_btn_aceptarTISeleccionedosActionPerformed

    private void btn_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmarActionPerformed
        // TODO add your handling code here:
        //asigna a cada TI los evaluadores seleccionados
    }//GEN-LAST:event_btn_ConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaAsignarEvaluadoresTI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaAsignarEvaluadoresTI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaAsignarEvaluadoresTI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaAsignarEvaluadoresTI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaAsignarEvaluadoresTI().setVisible(true);
               
            }
        });
    }
    
    // FALTAN METODOS
     public void mostrarNomYApeChair()
     {
         GestorAsignarEvaluadores ges = new GestorAsignarEvaluadores();
         lbl_Chair.setText("Chair: "+ ges.asignarEvaluadoresATI());
         lbl_simposio.setText("Nombre Edición de SImposio: "+ges.buscarEdicionSimposioChair().getNombre());
     }
    
     public void mostrarTIPendientes()
     {
         
     }
    /*   
        mostrarDatosAutores()
        mostrarEvaluadores()
        solicitarSeleccionarTrabajosInvestigacion()
        mostrarEvaluadoresDisponiblesPorTI()
        mostrarCantTIPorEvaluador()
    */
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPanePasos;
    private javax.swing.JButton btn_Ascendente;
    private javax.swing.JButton btn_Atras;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Confirmar;
    private javax.swing.JButton btn_Descendente;
    private javax.swing.JButton btn_aceptarTISeleccionedos;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lbl_Chair;
    private javax.swing.JLabel lbl_simposio;
    private javax.swing.JList<String> lista_CantTIPorEvaluador;
    private javax.swing.JList<String> lista_TIyEvaluadores;
    private javax.swing.JPanel pnl_paso1;
    private javax.swing.JPanel pnl_paso2;
    private javax.swing.JPanel pnl_paso3;
    private javax.swing.JPanel pnl_paso4;
    private javax.swing.JTable tbl_AutoresPorTI;
    private javax.swing.JTable tbl_Evaluadores;
    private javax.swing.JTable tbl_EvaluadoresDisponibles;
    private javax.swing.JTable tbl_TI;
    // End of variables declaration//GEN-END:variables
}
